apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <body>
    <h1>Hello from ArgoCD GitOps!</h1>
    <p>This app is deployed via ArgoCD</p>
    </body>
    </html>